[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["VITE_API_URL=https://sparkling-vitality-production-d3d5.up.railway.app/api npm run build"]

[start]
cmd = "npx serve dist -s --listen $PORT --no-clipboard"
